#drop down
CakewalkUAE/ui pull request #12
Opened 2023-09-18 10:15 UTC by shubhenducw

2023-09-18 13:20 UTC, raghavcakewalk commented on apps/www/registry/tui/example/cards/dropdown-card.tsx
> +} from "lucide-react"
Please organise imports if not used

2023-09-18 13:26 UTC, raghavcakewalk requested changes
changes

2023-09-19 04:51 UTC, raghavcakewalk commented on apps/www/registry/tui/example/cards/dropdown-card.tsx
> +  const [checked, setChecked] = React.useState(false);
```suggestion
  const [checked, setChecked] = React.useState<boolean>(false);
```

2023-09-19 04:52 UTC, raghavcakewalk commented on apps/www/registry/tui/example/cards/dropdown-card.tsx
> +                      data.isLabel ? <DropdownMenuLabel>{data.title}</DropdownMenuLabel>
```suggestion
                      data?.isLabel ? <DropdownMenuLabel>{data?.title}</DropdownMenuLabel>
```

2023-09-19 04:57 UTC, raghavcakewalk requested changes
need a core component and examples should be such that they are easily copy pasted
All the elements in data should be coming from props and all this if else checks should be moved to the core component

2023-09-19 10:11 UTC, shubhenducw commented
> need a core component and examples should be such that they are easily copy pasted All the elements in data should be coming from props and all this if else checks should be moved to the core component

Core components has all the required props

2023-09-19 10:40 UTC, sohebcakewalk approved these changes

2023-09-19 11:31 UTC, raghavcakewalk approved these changes

2023-09-19 15:46 UTC, raghavcakewalk approved these changes

2023-09-19 18:48 UTC, merged