Initial Commit for Text Area component
CakewalkUAE/ui pull request #21
Opened 2023-09-26 06:54 UTC by Parag27-cakewalk

http://cakewalkuae/softstudio-projectmanagement#468

2023-09-26 10:10 UTC, sohebcakewalk requested changes
Fix all the changes

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                            <ul className={cn("absolute right-0 z-10 mt-1 max-h-56 w-52 overflow-auto rounded-lg py-3 text-base shadow sm:text-sm", className)}>
@Parag27-cakewalk - Why fixed width and height?

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                            <ul className={cn("absolute right-0 z-10 mt-1 max-h-56 w-52 overflow-auto rounded-lg py-3 text-base shadow ring-1 ring-opacity-5 focus:outline-none sm:text-sm", className)
@Parag27-cakewalk  - Why fixed width and height?

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                            <ul className={cn("absolute right-0 z-10 mt-1 max-h-56 w-52 overflow-auto rounded-lg py-3 text-base shadow sm:text-sm", className)}>
@Parag27-cakewalk - Why fixed width and height?

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                              <div className={cn(`bg-${selectedIcon.bg} flex h-8 w-8 items-center justify-center rounded-full`, className)}>
@Parag27-cakewalk - Why fixed width and height?

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                          type="button" className={cn("inline-flex h-6 w-6 items-center justify-center rounded-full", className)}>
@Parag27-cakewalk - Why fixed width and height?

2023-09-26 10:10 UTC, sohebcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +                  <ul className={cn("absolute z-10 -ml-6 w-60 rounded-lg text-base shadow focus:outline-none sm:ml-auto w-64 text-sm", className)}>
@Parag27-cakewalk - Why fixed width and height?

2023-09-26 10:14 UTC, raghavcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +    const handleCommentButtonClick = () => {
wrap these in useCallbacks

2023-09-27 08:59 UTC, raghavcakewalk commented on apps/www/registry/tui/ui/textarea.tsx
> +    const handleCommentButtonClick = () => {
for example:  
   const handleWriteButtonClick = useCallback(() => {
      memoizedSetShowWrite(true);
      memoizedSetShowComment(false);
    }, []);
    
    It memoize the functions which returns the same result each time component renders.
    Make sure to momoize such functions or constants

2023-09-28 07:09 UTC, sohebcakewalk approved these changes

2023-09-28 07:09 UTC, merged