change the alignment of the breadcrumb variant
CakewalkUAE/ui pull request #41
Opened 2023-10-11 10:06 UTC by Parag27-cakewalk

https://github.com/CakewalkUAE/softstudio-projectmanagement/issues/468

2023-10-11 10:21 UTC, shubhenducw requested changes

2023-10-11 10:21 UTC, shubhenducw commented on apps/www/registry/tui/example/breadcrumbIcon.tsx
> +            <div className="text-m pt-11 font-bold text-primary pb-6">Full Width Bar</div>
what's text-m ? I see its been used in BreadCrumb, Button Group, Pagination, sidebar navigation, steps, text-area, notification

2023-10-11 11:11 UTC, shubhenducw commented
@Parag27-cakewalk 

did pnpm install
pnpm run build : failed

<img width="1499" alt="image" src="https://github.com/CakewalkUAE/ui/assets/90603428/577d87f3-5a93-4dda-8ef1-50853ea09f25">

2023-10-12 06:02 UTC, sohebcakewalk approved these changes

2023-10-12 08:23 UTC, shubhenducw approved these changes

2023-10-12 09:32 UTC, merged